language: elixir

elixir:
  - 1.2.2
otp_release:
  - 18.2.1

cache:
  directories:
    - _build
    - deps

before_script:
  - mix local.hex --force
  - mix deps.get --only test

script:
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
